import type { Metadata } from 'next';
import {
    Geist,
    Geist_Mono,
    IM_Fell_English,
    Bricolage_Grotesque,
} from 'next/font/google';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import CustomContextMenu from '@/components/context-menu/context-menu';
import { AppSidebar } from '@/components/sidebar/app-sidebar';

import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

const fell = IM_Fell_English({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-fell-english',
    display: 'swap',
});

const bricolage = Bricolage_Grotesque({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-bricolage-grotesque',
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${fell.variable} ${bricolage.variable} antialiased`}
            >
                <CustomContextMenu>
                    <SidebarProvider>
                        <AppSidebar />

                        <SidebarInset>{children}</SidebarInset>
                    </SidebarProvider>
                </CustomContextMenu>
            </body>
        </html>
    );
}
